name: Еден
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/55613e54-ce8d-4a81-a69f-40f9f6f04715.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d56eee95-6a18-470b-8ef4-8009cd45e0c9.png
layout_spectrum: 0.3578730579318091
typography_spectrum: 0.9396013935624005
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#B0CC99'
    - '#677E52'
    - '#B7CA79'
    - '#F6E8B1'
    - '#89725B'
  brandStrength: 0.4302520288465231
  lightness: 1
  saturation: 0.9175007374997777
  rhythmicContrast: 0.18255982038601865
purpose:
  - type: contact
    label: Пишите нам
    url: 'mailto:bojan.catic022@gmail.com'
  - type: contact
    label: Позовите нас
    url: 'tel:+38122497294'
title: Еден
description: Савремени узгој јагода на природан начин
author:
  name: Bojan Catic
  url: 'http://xn--d1abb6a.xn--90a3ac/'
  email: bojan.catic022@gmail.com
content_rating:
  adult: false
navigation:
  - name: О јагодама
    id: 2e830f54-d9fa-4c7b-88a3-4e91d9a5aa05
    type: content
  - name: Припрема и садња
    id: febeadb7-eac9-4e4e-b63d-306a54118996
    type: content
  - name: Одабир садног материјала
    id: f7247512-b1fe-4887-9938-817a9102fd31
    type: content
  - name: Ђубрење јагода
    id: 3b969090-e4b6-4893-ab9d-b8b6fde67ff9
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/cfe73cad-30f6-45a9-9fd1-8b64c7f9f10b.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/cfe73cad-30f6-45a9-9fd1-8b64c7f9f10b.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/8a2eee90-8229-4657-95b4-e3a96b852ad3.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/8a2eee90-8229-4657-95b4-e3a96b852ad3.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ed5ea005-6374-43bd-adf6-ff69c73e3902.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ed5ea005-6374-43bd-adf6-ff69c73e3902.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
