layout_spectrum: 0.8267830434792887
typography_spectrum: 0.18627670575182256
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.9979856047909338
  lightness: 0.06691277964852087
  saturation: 0.21865742726030177
  rhythmicContrast: 0.295513038184254
coverPrefs:
  filter: false
github: true
name: eden
navigation:
  - name: о Јагодама
    id: 2e830f54-d9fa-4c7b-88a3-4e91d9a5aa05
    type: content
  - name: Сорте
    id: 8e65451c-d5e5-4131-a79a-583a2d0c859c
    type: content
  - name: Припрема и садња
    id: febeadb7-eac9-4e4e-b63d-306a54118996
    type: content
  - name: Мултимедија
    id: 6e829739-2f54-472d-9894-d6046e967298
    type: content
title: Еден
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/cfe73cad-30f6-45a9-9fd1-8b64c7f9f10b.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/cfe73cad-30f6-45a9-9fd1-8b64c7f9f10b.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Савремени узгој јагода на природан начин
purpose:
  - type: contact
    url: 'mailto:office@eden.rs'
    label: пишите нам
  - type: contact
    url: 'tel:+38122497294'
    label: позовите нас
