typography_spectrum: 0.6156142264672804
content_rating:
  adult: false
color:
  brandColors:
    - '#B0CC99'
    - '#677E52'
    - '#B7CA79'
    - '#F6E8B1'
    - '#89725B'
  brandStrength: 0.874201027497852
  lightness: 0.2956815300053815
  saturation: 0.1133570328395408
  rhythmicContrast: 0.10235002973614869
github: true
layout_spectrum: 0.6019646995461149
name: Еден
title: Еден
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/cfe73cad-30f6-45a9-9fd1-8b64c7f9f10b.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/cfe73cad-30f6-45a9-9fd1-8b64c7f9f10b.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
coverPrefs:
  filter: false
description: Савремени узгој јагода на природан начин
purpose:
  - type: contact
    url: 'mailto:office@eden.rs'
    label: пишите нам
  - type: contact
    url: 'tel:+38122497294'
    label: позовите нас
